version: '3.4'

services:
  kantin:
    image: ${DOCKER_REGISTRY-}kantin
    build:
      context: .
      dockerfile: Kantin/Dockerfile
    links:  
      - sqlserver

  sqlserver:  
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'sqlserver'  
    environment:  
        ACCEPT_EULA: Y  
        SA_PASSWORD: "123Kantin!@#"  
    volumes:  
        - ./data/mssql:/var/opt/mssql3  
    ports:  
        - '1433:1433'  
    expose:  
        - 1433